
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3056:3000"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: moneymanager
    volumes:
      - .:/usr/src/app
    depends_on:
      - database

  database:
    image: postgres:13
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: